// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnDWymrduE_rTCgfN3sM5tqOqPlqXHHn8',
    appId: '1:218764459476:web:81779edee4df3f49dcaa41',
    messagingSenderId: '218764459476',
    projectId: 'learned-vortex-438615-j5',
    authDomain: 'learned-vortex-438615-j5.firebaseapp.com',
    storageBucket: 'learned-vortex-438615-j5.firebasestorage.app',
    measurementId: 'G-GHNQLFV5YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_z8Sa0woQZQ_P5FFl8VFLtBJbJqAzpsY',
    appId: '1:218764459476:android:5ad326a300a8d697dcaa41',
    messagingSenderId: '218764459476',
    projectId: 'learned-vortex-438615-j5',
    storageBucket: 'learned-vortex-438615-j5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEY1lsErxEXTfRHheVb0uDcuQ7YPrtDtw',
    appId: '1:218764459476:ios:4037b12b3078e89fdcaa41',
    messagingSenderId: '218764459476',
    projectId: 'learned-vortex-438615-j5',
    storageBucket: 'learned-vortex-438615-j5.firebasestorage.app',
    iosBundleId: 'com.example.internshipTaskFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEY1lsErxEXTfRHheVb0uDcuQ7YPrtDtw',
    appId: '1:218764459476:ios:4037b12b3078e89fdcaa41',
    messagingSenderId: '218764459476',
    projectId: 'learned-vortex-438615-j5',
    storageBucket: 'learned-vortex-438615-j5.firebasestorage.app',
    iosBundleId: 'com.example.internshipTaskFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnDWymrduE_rTCgfN3sM5tqOqPlqXHHn8',
    appId: '1:218764459476:web:eb9036f75def0d48dcaa41',
    messagingSenderId: '218764459476',
    projectId: 'learned-vortex-438615-j5',
    authDomain: 'learned-vortex-438615-j5.firebaseapp.com',
    storageBucket: 'learned-vortex-438615-j5.firebasestorage.app',
    measurementId: 'G-JFPY58K58R',
  );
}
